export const recentApplications = [
    {
      id: 1,
      position: "UI/UX Designer",
      company: "Aumbre",
      companyLogo: "/api/placeholder/60/60",
      logoBackground: "#6366f1",
      logoInitial: "A",
      location: "UK",
      type: "Full-time",
      status: "Interview",
      statusColor: "#3b82f6",
      appliedDate: "12/05/25"
    },
    {
      id: 2,
      position: "Frontend Developer",
      company: "Gamersback",
      companyLogo: "/api/placeholder/60/60",
      logoBackground: "#f59e0b",
      logoInitial: "G",
      location: "UK",
      type: "Full-time",
      status: "Pending",
      statusColor: "#f59e0b",
      appliedDate: "12/05/25"
    },
    {
      id: 3,
      position: "Product Designer",
      company: "Superworld",
      companyLogo: "/api/placeholder/60/60",
      logoBackground: "#818cf8",
      logoInitial: "S",
      location: "UK",
      type: "Full-time",
      status: "Rejected",
      statusColor: "#ef4444",
      appliedDate: "12/05/25"
    },
    {
      id: 4,
      position: "Product Designer",
      company: "Superworld",
      companyLogo: "/api/placeholder/60/60",
      logoBackground: "#818cf8",
      logoInitial: "S",
      location: "UK",
      type: "Full-time",
      status: "Rejected",
      statusColor: "#ef4444",
      appliedDate: "12/05/25"
    }
  ];


 export  const recommendedJobs = [
    {
      id: 1,
      position: "Senior Creative Designer",
      company: "ABC Design Private Limited",
      companyLogo: "/api/placeholder/60/60",
      location: "Manchester, UK",
      salary: "£525.00",
      tags: ["Actively Hiring", "Growing Fast"]
    },
    {
      id: 2,
      position: "Senior Creative Designer",
      company: "ABC Design Private Limited",
      companyLogo: "/api/placeholder/60/60",
      location: "Manchester, UK",
      salary: "£525.00",
      tags: ["Actively Hiring", "Growing Fast"]
    },
    {
      id: 3,
      position: "Senior Creative Designer",
      company: "ABC Design Private Limited",
      companyLogo: "/api/placeholder/60/60",
      location: "Manchester, UK",
      salary: "£525.00",
      tags: ["Actively Hiring", "Growing Fast"]
    },
    {
      id: 4,
      position: "Senior Creative Designer",
      company: "ABC Design Private Limited",
      companyLogo: "/api/placeholder/60/60",
      location: "Manchester, UK",
      salary: "£525.00",
      tags: ["Actively Hiring", "Growing Fast"]
    }
    ,
    {
      id: 5,
      position: "Senior Creative Designer",
      company: "ABC Design Private Limited",
      companyLogo: "/api/placeholder/60/60",
      location: "Manchester, UK",
      salary: "£525.00",
      tags: ["Actively Hiring", "Growing Fast"]
    }
  ];

export  const jobListings = [
    {
      id: 1,
      title: "Senior Creative Designer",
      company: "ABC Design Private Limited",
      location: "Manchester, UK",
      salary: "£525.00",
      logo: "h",
      logoColor: "bg-purple-600",
      activelyHiring: true,
      growingFast: true
    },
    {
      id: 2,
      title: "Graphic Designer",
      company: "ABC Design Private Limited",
      location: "Manchester, UK",
      salary: "£525.00",
      logo: "A",
      logoColor: "bg-blue-500",
      activelyHiring: true,
      growingFast: true
    },
    {
      id: 3,
      title: "Administrative Executive",
      company: "ABC Design Private Limited",
      location: "Manchester, UK",
      salary: "£525.00",
      logo: "O",
      logoColor: "bg-gray-700",
      activelyHiring: true,
      growingFast: true
    },
    {
      id: 4,
      title: "Software Tester",
      company: "ABC Design Private Limited",
      location: "Manchester, UK",
      salary: "£525.00",
      logo: "S",
      logoColor: "bg-blue-200 text-blue-600",
      activelyHiring: true,
      growingFast: true
    }
  ];


export  const applications = [
    {
      id: 1,
      position: 'UI/UX Designer',
      company: 'Aurore',
      location: 'UK, Full-time',
      status: 'Interview',
      statusColor: 'bg-blue-500',
      logo: 'A',
      logoColor: 'bg-indigo-500',
      applied: '12/05/25'
    },
    {
      id: 2,
      position: 'Frontend Developer',
      company: 'Gamersback',
      location: 'UK, Full-time',
      status: 'Pending',
      statusColor: 'bg-yellow-400',
      logo: 'G',
      logoColor: 'bg-gray-800',
      applied: '12/05/25'
    },
    {
      id: 3,
      position: 'Product Designer',
      company: 'Superworld',
      location: 'UK, Full-time',
      status: 'Rejected',
      statusColor: 'bg-red-500',
      logo: 'S',
      logoColor: 'bg-blue-300',
      applied: '12/05/25'
    },
    {
      id: 4,
      position: 'Product Designer',
      company: 'Superworld',
      location: 'UK, Full-time',
      status: 'Rejected',
      statusColor: 'bg-red-500',
      logo: 'S',
      logoColor: 'bg-blue-300',
      applied: '12/05/25'
    }
  ];


  export  const archiveApplications = [
    {
      id: 1,
      position: 'UI/UX Designer',
      company: 'Aurore',
      location: 'UK, Full-time',
      status: 'Interview',
      statusColor: 'bg-blue-500',
      logo: 'A',
      logoColor: 'bg-indigo-500',
      applied: '12/05/25'
    },
    {
      id: 2,
      position: 'Product Designer',
      company: 'Superworld',
      location: 'UK, Full-time',
      status: 'Rejected',
      statusColor: 'bg-red-500',
      logo: 'S',
      logoColor: 'bg-blue-300',
      applied: '12/05/25'
    }
  ];


  export const jobRoles = [
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Data Analyst",
  "Data Scientist",
  "Machine Learning Engineer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Software Engineer",
  "Mobile App Developer",
  "Android Developer",
  "iOS Developer",
  "UI/UX Designer",
  "Web Developer",
  "QA Engineer",
  "Automation Tester",
  "Game Developer",
  "Cybersecurity Analyst",
  "Information Security Specialist",
  "Network Engineer",
  "IT Support Specialist",
  "Database Administrator",
  "System Administrator",
  "Site Reliability Engineer",
  "AI Engineer",
  "Blockchain Developer",
  "Embedded Systems Engineer",
  "IoT Developer",
  "AR/VR Developer",
  "Robotics Engineer",
  "Technical Writer",
  "Product Manager",
  "Project Manager",
  "Business Analyst",
  "Scrum Master",
  "Software Architect",
  "Solutions Architect",
  "Salesforce Developer",
  "CRM Consultant",
  "ERP Consultant",
  "Tech Support Engineer",
  "Help Desk Technician",
  "IT Consultant",
  "SEO Specialist",
  "Digital Marketing Analyst",
  "Content Strategist",
  "Social Media Manager",
  "Graphic Designer",
  "Video Editor",
  "3D Animator",
  "Photographer",
  "Penetration Tester",
  "Ethical Hacker",
  "Game Designer",
  "Game Tester",
  "VR Designer",
  "AI Researcher",
  "Computer Vision Engineer",
  "NLP Engineer",
  "Big Data Engineer",
  "Hadoop Developer",
  "SAP Consultant",
  "Oracle Developer",
  "Python Developer",
  "Java Developer",
    "Technical Program Manager",
  "Innovation Manager",
  "Firmware Engineer",
  "VLSI Design Engineer",
  "FPGA Engineer",
  "Technical Account Manager",
  "Cloud Security Engineer",
  "Mobile Security Analyst",
  "IT Risk Analyst",
  "Infrastructure Engineer",
  "Network Security Engineer",
  "IT Governance Analyst",
  "Information Systems Manager",
  "Platform Engineer",
  "AI Ethics Researcher",
  "Data Engineer",
  "Data Architect",
  "Solutions Engineer",
  "Security Consultant",
  "Security Engineer",
  "Quantitative Analyst",
  "Financial Data Analyst",
  "Digital Forensics Analyst",
  "IT Project Coordinator",
  "Health Informatics Specialist",
  "EdTech Developer",
  "Agile Coach",
  "Scrum Product Owner",
  "Tech Evangelist",
  "Cloud Migration Engineer",
  "Business Intelligence Developer",
  "IT Compliance Analyst",
  "Database Architect",
  "IT Trainer",
  "Research Software Engineer",
  "IT Asset Manager",
  "Application Support Engineer",
  "Security Operations Center Analyst (SOC Analyst)",
  "Logistics Software Engineer",
  "Legal Tech Consultant",
  "InsurTech Developer",
  "FinTech Product Manager",
  "SaaS Engineer",
  "CRM Specialist",
  "Data Compliance Officer",
  "Knowledge Management Specialist",
  "Telecom Engineer",
  "E-commerce Tech Lead",
  "Streaming Platform Engineer",
  "DevRel Engineer",
  "JavaScript Developer",
  "TypeScript Developer",
  "C++ Developer",
  "C# Developer",
  "Go Developer",
  "Rust Developer",
  "PHP Developer",
  "Ruby on Rails Developer",
  "Perl Developer",
  "Scala Developer",
  "Technical Recruiter",
  "Cloud Consultant",
  "Azure Engineer",
  "AWS Engineer",
  "GCP Engineer",
  "Kubernetes Specialist",
  "Docker Expert",
  "CI/CD Engineer",
  "NoSQL Developer",
  "MongoDB Specialist",
  "PostgreSQL Developer",
  "MySQL Developer",
  "Linux Administrator",
  "Windows Server Engineer",
  "IT Auditor",
  "CTO",
  "Software Tester",
  "Tech Support Specialist",
  "Computer Programmer",
  "Hardware Engineer",
  "Biomedical Engineer",
  "Research Scientist",
  "Mathematician",
  "Statistician",
  "Simulation Engineer"
];


