
export const timeFormatOptions = [
    { label: 'Hourly Rate', value: 'hourly' },
    { label: 'Daily Rate', value: 'daily' },
    { label: 'Weekly Rate', value: 'weekly' },
    { label: 'Monthly Rate', value: 'monthly' },
    { label: 'Annual Rate', value: 'annual' }
];


export const prospectiveRolesOptions = [
    { label: 'Care workers and home carers', value: 'Care workers and home carers' },
    { label: 'Senior care workers', value: 'Senior care workers' },
    { label: 'Residential day and domiciliary care managers and proprietors', value: 'Residential day and domiciliary care managers and proprietors' },
    { label: 'Generalist Medical Practitioners', value: 'Generalist Medical Practitioners' },
    { label: 'Specialist Medical Practitioners', value: 'Specialist Medical Practitioners' },
    { label: 'Physiotherapists [Inactive]', value: 'Physiotherapists [Inactive]' },
    { label: 'Occupational Therapists [Inactive]', value: 'Occupational Therapists [Inactive]' },
    { label: 'Speech and Language Therapists [Inactive]', value: 'Speech and Language Therapists [Inactive]' },
    { label: 'Psychotherapists and cognitive behaviour therapists [Inactive]', value: 'Psychotherapists and cognitive behaviour therapists [Inactive]' },
    { label: 'Clinical Psychologists [Inactive]', value: 'Clinical Psychologists [Inactive]' },
    { label: 'Other Psychologists [Inactive]', value: 'Other Psychologists [Inactive]' },
    { label: 'Midwifery Nurses [Inactive]', value: 'Midwifery Nurses [Inactive]' },
    { label: 'Registered community nurses [Inactive]', value: 'Registered community nurses [Inactive]' },
    { label: 'Registered specialist nurses [Inactive]', value: 'Registered specialist nurses [Inactive]' },
    { label: 'Registered nurse practitioners [Inactive]', value: 'Registered nurse practitioners [Inactive]' },
    { label: 'Registered mental health nurses [Inactive]', value: 'Registered mental health nurses' },
    { label: 'Registered children’s nurses [Inactive]', value: 'Registered children’s nurses [Inactive]' },
    { label: 'Dental nurses [Inactive]', value: 'Dental nurses [Inactive]' },
    { label: 'Health associate professionals not elsewhere classified [Inactive]', value: 'Health associate professionals not elsewhere classified [Inactive]' },
    { label: 'Ambulance Staff [Inactive]', value: 'Ambulance Staff [Inactive]' },
    { label: 'Other registered nursing professionals [Inactive]', value: 'Other registered nursing professionals [Inactive]' },
    { label: 'Pharmacists [Inactive]', value: 'Pharmacists [Inactive]' },
    { label: 'Optometrists [Inactive]', value: 'Optometrists [Inactive]' },
    { label: 'Dental Practitioners', value: 'Dental Practitioners' },
    { label: 'Medical Radiographers [Inactive]', value: 'Medical Radiographers [Inactive]' },
    { label: 'Paramedics [Inactive]', value: 'Paramedics [Inactive]' },
    { label: 'Podiatrists [Inactive]', value: 'Podiatrists [Inactive]' },
    { label: 'Social workers [Inactive]', value: 'Social workers [Inactive]' },
    { label: 'Other health professionals not elsewhere classified [Inactive]', value: 'Other health professionals not elsewhere classified [Inactive]' },
    { label: 'Chief executives and senior officials', value: 'Chief executives and senior officials' },
    { label: 'Production managers and directors in manufacturing', value: 'Production managers and directors in manufacturing' },
    { label: 'Production managers and directors in construction', value: 'Production managers and directors in construction' },
    { label: 'Production managers and directors in mining and energy', value: 'Production managers and directors in mining and energy' },
    { label: 'Financial managers and directors', value: 'Financial managers and directors' },
    { label: 'Marketing sales and advertising directors', value: 'Marketing sales and advertising directors' },
    { label: 'Public relations and communications directors', value: 'Public relations and communications directors' },
    { label: 'Purchasing managers and directors', value: 'Purchasing managers and directors' },
    { label: 'Charitable organisation managers and directors', value: 'Charitable organisation managers and directors' },
    { label: 'Human resource managers and directors', value: 'Human resource managers and directors' },
    { label: 'Information technology directors', value: 'Information technology directors' },
    { label: 'Functional managers and directors not elsewhere classified', value: 'Functional managers and directors not elsewhere classified' },
    { label: 'Directors in logistics warehousing and transport', value: 'Directors in logistics warehousing and transport' },
    { label: 'Managers and directors in retail and wholesale', value: 'Managers and directors in retail and wholesale' },
    { label: 'Senior police officers', value: 'Senior police officers' },
    { label: 'Senior officers in fire; ambulance; prison and related services', value: 'Senior officers in fire; ambulance; prison and related services' },
    { label: 'Health services and public health managers and directors', value: 'Health services and public health managers and directors' },
    { label: 'Social services managers and directors', value: 'Social services managers and directors' },
    { label: 'Managers and proprietors in agriculture and horticulture', value: 'Managers and proprietors in agriculture and horticulture' },
    { label: 'Managers and proprietors in forestry; fishing and related services', value: 'Managers and proprietors in forestry; fishing and related services' },
    { label: 'Hotel and accommodation managers and proprietors', value: 'Hotel and accommodation managers and proprietors' },
    { label: 'Restaurant and catering establishment managers and proprietors', value: 'Restaurant and catering establishment managers and proprietors' },
    { label: 'Publicans and managers of licensed premises', value: 'Publicans and managers of licensed premises' },
    { label: 'Leisure and sports managers and proprietors', value: 'Leisure and sports managers and proprietors' },
    { label: 'Travel agency managers and proprietors', value: 'Travel agency managers and proprietors' },
    { label: 'Health care practice managers', value: 'Health care practice managers' },
    { label: 'Early education and childcare services proprietors', value: 'Early education and childcare services proprietors' },
    { label: 'Managers in transport and distribution', value: 'Managers in transport and distribution' },
    { label: 'Managers in storage and warehousing', value: 'Managers in storage and warehousing' },
    { label: 'Managers in logistics', value: 'Managers in logistics' },
    { label: 'Property; housing and estate managers', value: 'Property; housing and estate managers' },
    { label: 'Garage managers and proprietors', value: 'Garage managers and proprietors' },
    { label: 'Hairdressing and beauty salon managers and proprietors', value: 'Hairdressing and beauty salon managers and proprietors' },
    { label: 'Waste disposal and environmental services managers', value: 'Waste disposal and environmental services managers' },
    { label: 'Managers and directors in the creative industries', value: 'Managers and directors in the creative industries' },
    { label: 'Betting shop and gambling establishment managers', value: 'Betting shop and gambling establishment managers' },
    { label: 'Hire services managers and proprietors', value: 'Hire services managers and proprietors' },
    { label: 'Directors in consultancy services', value: 'Directors in consultancy services' },
    { label: 'Managers and proprietors in other services not elsewhere classified', value: 'Managers and proprietors in other services not elsewhere classified' },
    { label: 'Chemical scientists', value: 'Chemical scientists' },
    { label: 'Biological scientists', value: 'Biological scientists' },
    { label: 'Biochemists and biomedical scientists', value: 'Biochemists and biomedical scientists' },
    { label: 'Physical scientists', value: 'Physical scientists' },
    { label: 'Social and humanities scientists', value: 'Social and humanities scientists' },
    { label: 'Natural and social science professionals not elsewhere classified', value: 'Natural and social science professionals not elsewhere classified' },
    { label: 'Civil engineers', value: 'Civil engineers' },
    { label: 'Mechanical engineers', value: 'Mechanical engineers' },
    { label: 'Electrical engineers', value: 'Electrical engineers' },
    { label: 'Electronics engineers', value: 'Electronics engineers' },
    { label: 'Production and process engineers', value: 'Production and process engineers' },
    { label: 'Aerospace engineers', value: 'Aerospace engineers' },
    { label: 'Engineering project managers and project engineers', value: 'Engineering project managers and project engineers' },
    { label: 'Engineering professionals not elsewhere classified', value: 'Engineering professionals not elsewhere classified' },
    { label: 'IT project managers', value: 'IT project managers' },
    { label: 'IT managers', value: 'IT managers' },
    { label: 'IT business analysts; architects and systems designers', value: 'IT business analysts; architects and systems designers' },
    { label: 'Programmers and software development professionals', value: 'Programmers and software development professionals' },
    { label: 'Cyber security professionals', value: 'Cyber security professionals' },
    { label: 'IT quality and testing professionals', value: 'IT quality and testing professionals' },
    { label: 'IT network professionals', value: 'IT network professionals' },
    { label: 'Information technology professionals not elsewhere classified', value: 'Information technology professionals not elsewhere classified' },
    { label: 'Web design professionals', value: 'Web design professionals' },
    { label: 'Graphic and multimedia designers', value: 'Graphic and multimedia designers' },
    { label: 'Conservation professionals', value: 'Conservation professionals' },
    { label: 'Environment professionals', value: 'Environment professionals' },
    { label: 'Research and development (r&d) managers', value: 'Research and development (r&d) managers' },
    { label: 'Other researchers; unspecified discipline', value: 'Other researchers; unspecified discipline' },
    { label: 'Veterinarians', value: 'Veterinarians' },
    { label: 'Higher education teaching professionals', value: 'Higher education teaching professionals' },
    { label: 'Teachers of english as a foreign language', value: 'Teachers of english as a foreign language' },
    { label: 'Teaching professionals not elsewhere classified', value: 'Teaching professionals not elsewhere classified' },
];

export const countryOptions = [
    { label: 'Afghanistan', value: 'Afghanistan' },
    { label: 'Albania', value: 'Albania' },
    { label: 'Algeria', value: 'Algeria' },
    { label: 'Andorra', value: 'Andorra' },
    { label: 'Angola', value: 'Angola' },
    { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
    { label: 'Argentina', value: 'Argentina' },
    { label: 'Armenia', value: 'Armenia' },
    { label: 'Australia', value: 'Australia' },
    { label: 'Austria', value: 'Austria' },
    { label: 'Azerbaijan', value: 'Azerbaijan' },
    { label: 'Bahamas', value: 'Bahamas' },
    { label: 'Bahrain', value: 'Bahrain' },
    { label: 'Bangladesh', value: 'Bangladesh' },
    { label: 'Barbados', value: 'Barbados' },
    { label: 'Belarus', value: 'Belarus' },
    { label: 'Belgium', value: 'Belgium' },
    { label: 'Belize', value: 'Belize' },
    { label: 'Benin', value: 'Benin' },
    { label: 'Bhutan', value: 'Bhutan' },
    { label: 'Bolivia', value: 'Bolivia' },
    { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
    { label: 'Botswana', value: 'Botswana' },
    { label: 'Brazil', value: 'Brazil' },
    { label: 'Brunei', value: 'Brunei' },
    { label: 'Bulgaria', value: 'Bulgaria' },
    { label: 'Burkina Faso', value: 'Burkina Faso' },
    { label: 'Burundi', value: 'Burundi' },
    { label: 'Cabo Verde', value: 'Cabo Verde' },
    { label: 'Cambodia', value: 'Cambodia' },
    { label: 'Cameroon', value: 'Cameroon' },
    { label: 'Canada', value: 'Canada' },
    { label: 'Central African Republic', value: 'Central African Republic' },
    { label: 'Chad', value: 'Chad' },
    { label: 'Chile', value: 'Chile' },
    { label: 'China', value: 'China' },
    { label: 'Colombia', value: 'Colombia' },
    { label: 'Comoros', value: 'Comoros' },
    { label: 'Costa Rica', value: 'Costa Rica' },
    { label: 'Côte d’Ivoire', value: 'Côte d’Ivoire' },
    { label: 'Croatia', value: 'Croatia' },
    { label: 'Cuba', value: 'Cuba' },
    { label: 'Cyprus', value: 'Cyprus' },
    { label: 'Czechia', value: 'Czechia' },
    { label: 'Democratic Republic of the Congo', value: 'Democratic Republic of the Congo' },
    { label: 'Denmark', value: 'Denmark' },
    { label: 'Djibouti', value: 'Djibouti' },
    { label: 'Dominica', value: 'Dominica' },
    { label: 'Dominican Republic', value: 'Dominican Republic' },
    { label: 'Ecuador', value: 'Ecuador' },
    { label: 'Egypt', value: 'Egypt' },
    { label: 'El Salvador', value: 'El Salvador' },
    { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
    { label: 'Eritrea', value: 'Eritrea' },
    { label: 'Estonia', value: 'Estonia' },
    { label: 'Eswatini', value: 'Eswatini' },
    { label: 'Ethiopia', value: 'Ethiopia' },
    { label: 'Fiji', value: 'Fiji' },
    { label: 'Finland', value: 'Finland' },
    { label: 'France', value: 'France' },
    { label: 'Gabon', value: 'Gabon' },
    { label: 'Gambia', value: 'Gambia' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Germany', value: 'Germany' },
    { label: 'Ghana', value: 'Ghana' },
    { label: 'Greece', value: 'Greece' },
    { label: 'Grenada', value: 'Grenada' },
    { label: 'Guatemala', value: 'Guatemala' },
    { label: 'Guinea', value: 'Guinea' },
    { label: 'Guinea‑Bissau', value: 'Guinea‑Bissau' },
    { label: 'Guyana', value: 'Guyana' },
    { label: 'Haiti', value: 'Haiti' },
    { label: 'Honduras', value: 'Honduras' },
    { label: 'Hungary', value: 'Hungary' },
    { label: 'Iceland', value: 'Iceland' },
    { label: 'India', value: 'India' },
    { label: 'Indonesia', value: 'Indonesia' },
    { label: 'Iran', value: 'Iran' },
    { label: 'Iraq', value: 'Iraq' },
    { label: 'Ireland', value: 'Ireland' },
    { label: 'Israel', value: 'Israel' },
    { label: 'Italy', value: 'Italy' },
    { label: 'Jamaica', value: 'Jamaica' },
    { label: 'Japan', value: 'Japan' },
    { label: 'Jordan', value: 'Jordan' },
    { label: 'Kazakhstan', value: 'Kazakhstan' },
    { label: 'Kenya', value: 'Kenya' },
    { label: 'Kiribati', value: 'Kiribati' },
    { label: 'Kuwait', value: 'Kuwait' },
    { label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
    { label: 'Laos', value: 'Laos' },
    { label: 'Latvia', value: 'Latvia' },
    { label: 'Lebanon', value: 'Lebanon' },
    { label: 'Lesotho', value: 'Lesotho' },
    { label: 'Liberia', value: 'Liberia' },
    { label: 'Libya', value: 'Libya' },
    { label: 'Liechtenstein', value: 'Liechtenstein' },
    { label: 'Lithuania', value: 'Lithuania' },
    { label: 'Luxembourg', value: 'Luxembourg' },
    { label: 'Madagascar', value: 'Madagascar' },
    { label: 'Malawi', value: 'Malawi' },
    { label: 'Malaysia', value: 'Malaysia' },
    { label: 'Maldives', value: 'Maldives' },
    { label: 'Mali', value: 'Mali' },
    { label: 'Malta', value: 'Malta' },
    { label: 'Marshall Islands', value: 'Marshall Islands' },
    { label: 'Mauritania', value: 'Mauritania' },
    { label: 'Mauritius', value: 'Mauritius' },
    { label: 'Mexico', value: 'Mexico' },
    { label: 'Micronesia', value: 'Micronesia' },
    { label: 'Moldova', value: 'Moldova' },
    { label: 'Monaco', value: 'Monaco' },
    { label: 'Mongolia', value: 'Mongolia' },
    { label: 'Montenegro', value: 'Montenegro' },
    { label: 'Morocco', value: 'Morocco' },
    { label: 'Mozambique', value: 'Mozambique' },
    { label: 'Myanmar', value: 'Myanmar' },
    { label: 'Namibia', value: 'Namibia' },
    { label: 'Nauru', value: 'Nauru' },
    { label: 'Nepal', value: 'Nepal' },
    { label: 'Netherlands', value: 'Netherlands' },
    { label: 'New Zealand', value: 'New Zealand' },
    { label: 'Nicaragua', value: 'Nicaragua' },
    { label: 'Niger', value: 'Niger' },
    { label: 'Nigeria', value: 'Nigeria' },
    { label: 'North Macedonia', value: 'North Macedonia' },
    { label: 'Norway', value: 'Norway' },
    { label: 'Oman', value: 'Oman' },
    { label: 'Pakistan', value: 'Pakistan' },
    { label: 'Palau', value: 'Palau' },
    { label: 'Panama', value: 'Panama' },
    { label: 'Papua New Guinea', value: 'Papua New Guinea' },
    { label: 'Paraguay', value: 'Paraguay' },
    { label: 'Peru', value: 'Peru' },
    { label: 'Philippines', value: 'Philippines' },
    { label: 'Poland', value: 'Poland' },
    { label: 'Portugal', value: 'Portugal' },
    { label: 'Qatar', value: 'Qatar' },
    { label: 'Republic of Korea', value: 'Republic of Korea' },
    { label: 'Republic of Moldova', value: 'Republic of Moldova' },
    { label: 'Romania', value: 'Romania' },
    { label: 'Russian Federation', value: 'Russian Federation' },
    { label: 'Rwanda', value: 'Rwanda' },
    { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis' },
    { label: 'Saint Lucia', value: 'Saint Lucia' },
    { label: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines' },
    { label: 'Samoa', value: 'Samoa' },
    { label: 'San Marino', value: 'San Marino' },
    { label: 'Sao Tomé and Príncipe', value: 'Sao Tomé and Príncipe' },
    { label: 'Saudi Arabia', value: 'Saudi Arabia' },
    { label: 'Senegal', value: 'Senegal' },
    { label: 'Serbia', value: 'Serbia' },
    { label: 'Seychelles', value: 'Seychelles' },
    { label: 'Sierra Leone', value: 'Sierra Leone' },
    { label: 'Singapore', value: 'Singapore' },
    { label: 'Slovakia', value: 'Slovakia' },
    { label: 'Slovenia', value: 'Slovenia' },
    { label: 'Solomon Islands', value: 'Solomon Islands' },
    { label: 'Somalia', value: 'Somalia' },
    { label: 'South Africa', value: 'South Africa' },
    { label: 'South Sudan', value: 'South Sudan' },
    { label: 'Spain', value: 'Spain' },
    { label: 'Sri Lanka', value: 'Sri Lanka' },
    { label: 'Sudan', value: 'Sudan' },
    { label: 'Suriname', value: 'Suriname' },
    { label: 'Sweden', value: 'Sweden' },
    { label: 'Switzerland', value: 'Switzerland' },
    { label: 'Syrian Arab Republic', value: 'Syrian Arab Republic' },
    { label: 'Tajikistan', value: 'Tajikistan' },
    { label: 'Thailand', value: 'Thailand' },
    { label: 'Timor‑Leste', value: 'Timor‑Leste' },
    { label: 'Togo', value: 'Togo' },
    { label: 'Tonga', value: 'Tonga' },
    { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
    { label: 'Tunisia', value: 'Tunisia' },
    { label: 'Türkiye', value: 'Türkiye' },
    { label: 'Tuvalu', value: 'Tuvalu' },
    { label: 'Uganda', value: 'Uganda' },
    { label: 'Ukraine', value: 'Ukraine' },
    { label: 'United Arab Emirates', value: 'United Arab Emirates' },
    { label: 'United Kingdom', value: 'United Kingdom' },
    { label: 'United Republic of Tanzania', value: 'United Republic of Tanzania' },
    { label: 'United States of America', value: 'United States of America' },
    { label: 'Uruguay', value: 'Uruguay' },
    { label: 'Uzbekistan', value: 'Uzbekistan' },
    { label: 'Vanuatu', value: 'Vanuatu' },
    { label: 'Venezuela', value: 'Venezuela' },
    { label: 'Viet Nam', value: 'Viet Nam' },
    { label: 'Yemen', value: 'Yemen' },
    { label: 'Zambia', value: 'Zambia' },
    { label: 'Zimbabwe', value: 'Zimbabwe' },
];

export const sectorOptions = [
    { value: 'accommodation-food-service', label: 'Accommodation and Food Service Activities' },
    { value: 'extraterritorial-organisations', label: 'Activities of extraterritorial organisations and bodies' },
    { value: 'household-employers', label: 'Activities of households as employers; production activities of household for own use' },
    { value: 'admin-support-service', label: 'Administrative and Support Service Activities' },
    { value: 'agriculture-forestry-fishing', label: 'Agriculture, Forestry and Fishing' },
    { value: 'arts-entertainment-recreation', label: 'Arts, Entertainment and Recreation' },
    { value: 'construction', label: 'Construction' },
    { value: 'education', label: 'Education' },
    { value: 'utilities', label: 'Electricity, gas, steam and air conditioning supply' },
    { value: 'finance-insurance', label: 'Financial and Insurance Activities' },
    { value: 'health-social-work', label: 'Human Health and Social Work Activities' },
    { value: 'information-communications', label: 'Information and Communications' },
    { value: 'manufacturing', label: 'Manufacturing' },
    { value: 'mining-quarrying', label: 'Mining and Quarrying' },
    { value: 'other-services', label: 'Other Service Activities' },
    { value: 'professional-scientific-technical', label: 'Professional, Scientific and Technical Activities' },
    { value: 'public-admin-defence', label: 'Public Admin and defence; compulsory social security' },
    { value: 'real-estate', label: 'Real Estate Activities' },
    { value: 'transportation-storage', label: 'Transportation and Storage' },
    { value: 'water-waste-management', label: 'Water supply; sewerage, waste management and remediation activities' },
    { value: 'wholesale-retail-trade', label: 'Wholesale and retail trade; repair of motor vehicles and motorcycles' }
];

export const companyTypeOptions = [
    { value: 'branch-office-overseas-company', label: 'Branch Office of an Overseas Company' },
    { value: 'central-local-gov-body-quango', label: 'Central/Local Gov. Dept; Body; Quango, Agency Public Body' },
    { value: 'charity', label: 'Charity' },
    { value: 'industrial-provident-society-1968', label: 'Co Inc under the Industrial & Provident Societies Act 1968' },
    { value: 'company-limited-by-guarantee', label: 'Company limited by Guarantee' },
    { value: 'hotel-catering-establishment', label: 'Hotel and/or Catering Establishment' },
    { value: 'incorporated-by-royal-charter', label: 'Incorporated by Royal Charter' },
    { value: 'limited-liability-partnership', label: 'Limited Liability Partnership' },
    { value: 'limited-partnership', label: 'Limited Partnership' },
    { value: 'overseas-government-international-organisation', label: 'Overseas Gov. Int. Organisation, Diplomatic Mission' },
    { value: 'partnership', label: 'Partnership' },
    { value: 'private-individual', label: 'Private Individual' },
    { value: 'private-limited-company', label: 'Private Limited Company/Limited Liability Company' },
    { value: 'public-limited-company', label: 'Public Limited Company' },
    { value: 'religious-faith-body', label: 'Religious and/or Faith Body' },
    { value: 'representative-office-overseas-company', label: 'Representative Office of an Overseas Company' },
    { value: 'sole-trader', label: 'Sole Trader' },
    { value: 'unlimited-company', label: 'Unlimited Company' }
];

export const tradingLengthOptions = [
    { value: '0-6-months', label: '0 to 6 months' },
    { value: '6-12-months', label: '6 to 12 months' },
    { value: '12-18-months', label: '12 to 18 months' },
    { value: '18-36-months', label: '18 to 36 months' },
    { value: '36-plus-months', label: '36+ months' }
];

export const entityTypeOptions = [
    { value: 'franchise', label: 'Franchise' },
    { value: 'group-of-branches', label: 'Group of Branches' },
    { value: 'head-office', label: 'Head Office' },
    { value: 'head-office-uk-branches', label: 'Head Office and all United Kingdom Branches' },
    { value: 'other', label: 'Other' },
    { value: 'parent-with-subsidiaries', label: 'Parent Company with Subsidiaries' },
    { value: 'single-body', label: 'Single Body' },
    { value: 'subsidiary', label: 'Subsidiary of a Parent Company' },
    { value: 'uk-branch', label: 'United Kingdom Branch' }
];



